---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/mysql64_2
    driver:
      box: mysql64_2
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
